# Arquivo de orquestração de compilação do ZMK
include:
  - board: nice_nano_v2
    shield: sofle_left
    artifact-name: sofle_left
    cmake-args: -DCONF_FILE="config/sofle.conf;config/sofle_left.conf"

  - board: nice_nano_v2
    shield: sofle_right
    artifact-name: sofle_right
    cmake-args: -DCONF_FILE="config/sofle.conf;config/sofle_right.conf"
