# Ativar Display OLED e I2C
CONFIG_ZMK_DISPLAY=y
CONFIG_I2C=y

# Habilitar ZMK Studio
CONFIG_ZMK_STUDIO=y

# Suporte para Encoders Rotativos
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Configurações de Conectividade e USB
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
# Prioriza USB quando o cabo está conectado
CONFIG_ZMK_USB_BOOTLOADER=y

# Gerenciamento de Energia
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Potência do Bluetooth
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Habilita suporte do ZMK para encoders
CONFIG_ZMK_ENCODER=y
