# Ativar Display OLED
CONFIG_ZMK_DISPLAY=y

# Habilitar ZMK Studio
CONFIG_ZMK_STUDIO=y

# Suporte para Encoders Rotativos
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Gerenciamento de Energia
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Forçar reconhecimento USB (Wired Mode)
CONFIG_ZMK_USB=y
