# Lado esquerdo: metade central do split
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# USB disponível apenas no lado central
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_BOOTLOADER=y

# Periféricos presentes nesta metade
CONFIG_ZMK_DISPLAY=y
CONFIG_I2C=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
