# Split BLE
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BLE=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y

# OLED SSD1306 em I2C
CONFIG_ZMK_DISPLAY=y
CONFIG_I2C=y
CONFIG_SSD1306=y

# Encoder EC11
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_ENCODER=y

# Energia
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Manter RGB/LED OFF (sem underglow/ws2812/neopixel)
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_BACKLIGHT=n
